name: dotnet-build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: restore
        run: dotnet restore
      
      
